spring:
  main:
    banner-mode: off

logging:
  level:
    root: info
    drrename: debug
    com:
      ulisesbocchio: warn
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %magenta([%thread]) %yellow(%logger{20}.%M\\(%class{0}.java:%line\\)) - %msg%throwable%n"
  file:
    name: ${app.settings.log-file}

app:
  name: drrename
  debug: false
  settings:
    parent: ${user.home}
    dir: ${app.settings.parent}/.${app.name}
    log-file: ${app.settings.dir}/${app.name}.log
  ui:
    appTitle: "Dr.Rename"
    initialWidth: 600
    initialHeight: 600
#    override-locale: de
  word-cnt: 3
  loop-delay-ms: 300
  reset-delay-ms: 500

