spring:
  main:
    web:
      application-type: none
    banner-mode: off

logging:
  level:
    root: info
    drrename: debug

app:
  ui:
    appTitle: "Dr.Rename"
    initialWidth: 600
    initialHeight: 600
  word-cnt: 3
  loop-delay-ms: 500
  reset-delay-ms: 2000
  debug: true

